version: "3"

services:
  vc-list-bot:
    image: docker.pkg.github.com/approvers/vc-list-bot/vc-list-bot:1.0.1
    container_name: vc-list-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${VC_LIST_BOT_DISCORD_TOKEN}
