version: "3"

services:
  imperial-police:
    image: docker.pkg.github.com/approvers/imperial-police/imperial-police:1.0.0
    container_name: imperial-police
    restart: unless-stopped
    environment:
      - IMPERIAL_POLICE_TOKEN=${IMPERIAL_POLICE_TOKEN}
