version: "3"

service:
  genkai-dictionary:
    image: docker.pkg.github.com/approvers/genkai-dictionary/genkai-dictionary:1.0.0
    container_name: genkai-dictionary
    environment:
      - DISCORD_TOKEN=${GENKAI_DICTIONARY_DISCORD_TOKEN}
      - GENKAI_DICTIONARY_DISCORD_BOT_SETTING_JSON_B64=${GENKAI_DICTIONARY_DISCORD_BOT_SETTING_JSON_B64}
      - GENKAI_DICTIONARY_FIREBASE_SETTING_JSON_B64=${GENKAI_DICTIONARY_FIREBASE_SETTING_JSON_B64}
